version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: population_db
      POSTGRES_USER: population_user
      POSTGRES_PASSWORD: population123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U population_user -d population_db" ]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    restart: always
    ports:
      - "8502:8502"
    environment:
      DATABASE_URL: postgresql://population_user:population123@db:5432/population_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    command: streamlit run app/population_density.py --server.port=8502 --server.address=0.0.0.0

volumes:
  postgres_data:
