name: Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run basic tests
      run: |
        # Test imports
        python -c "import streamlit, pandas, sqlalchemy, psycopg2; print('✅ All core imports successful')"
        python -c "import plotly, geopandas; print('✅ All visualization imports successful')"

    - name: Check file structure
      run: |
        ls -la
        test -f app/population\ density.py && echo "✅ Main app file exists"
        test -f requirements.txt && echo "✅ Requirements file exists"
        test -f README.md && echo "✅ Documentation exists"
